export interface SIFund {
  id: string;
  name: string;
  shortName: string;
  amc: string;
  amcCode: string;
  category: string;
  categorySlug: string;
  inceptionDate: string;
  inceptionNav: number;
  currentNav: number;
  ter: number;
  terRegular: number;
  minInvestment: number;
  redemptionFreq: string;
  settlement: string;
  exitLoad: string;
  benchmark: string;
  slug: string;
  seoTitle: string;
  seoDesc: string;
  navHistory: { month: string; nav: number | null }[];
  monthlyReturns: Record<string, number | null>;
  returns: {
    oneMonth: number | null;
    threeMonth: number | null;
    sinceInception: number;
  };
  managers: string[];
  strategyType: string;
  netLongRange: string;
  marchCrashData: {
    fundReturn: number | null;
    niftyReturn: number;
    capitalProtected: number | null;
    alphaVsNifty: number | null;
    categoryAvg: number;
    vsCategory: number | null;
    rank: number | null;
    totalFunds: number;
  };
  quizProfile: {
    riskLevel: string;
    strategyClarity: string;
    amcTrust: string;
    bestFor: string[];
  };
}

export const sifFunds: SIFund[] = [
  // 1. Altiva Hybrid Long-Short (Edelweiss)
  {
    id: 'altiva-hybrid-long-short',
    name: 'Altiva Hybrid Long-Short',
    shortName: 'Altiva',
    amc: 'Edelweiss',
    amcCode: 'ED',
    category: 'Hybrid Long Short',
    categorySlug: 'hybrid-long-short',
    inceptionDate: '2025-10-24',
    inceptionNav: 10.0102,
    currentNav: 10.3174,
    ter: 1.35,
    terRegular: 2.25,
    minInvestment: 1000000,
    redemptionFreq: '2x per week (Mon & Wed)',
    settlement: 'T+3',
    exitLoad: '0.50% if redeemed within 90 days',
    benchmark: 'NIFTY 50 Hybrid Composite Debt 50:50',
    slug: 'altiva-hybrid-long-short',
    seoTitle: 'Altiva SIF by Edelweiss — Returns, NAV & Analysis',
    seoDesc: 'Altiva Hybrid Long-Short SIF returned +2.10% since inception while Nifty fell 11.3% in March 2026.',
    navHistory: [
      { month: 'Oct 2025', nav: 10.0102 },
      { month: 'Nov 2025', nav: 10.12 },
      { month: 'Dec 2025', nav: 10.18 },
      { month: 'Jan 2026', nav: 10.25 },
      { month: 'Feb 2026', nav: 10.40 },
      { month: 'Mar 2026', nav: 10.3174 },
      { month: 'Apr 2026', nav: null },
    ],
    monthlyReturns: {
      'Oct 2025': 0.00,
      'Nov 2025': 1.10,
      'Dec 2025': 0.59,
      'Jan 2026': 0.69,
      'Feb 2026': 1.46,
      'Mar 2026': -0.80,
      'Apr 2026': null,
    },
    returns: {
      oneMonth: -1.42,
      threeMonth: -0.80,
      sinceInception: 2.10,
    },
    managers: ['Bhavesh Jain', 'Bharat Lahoti', 'Dhawal Dalal', 'Pranavi Kulkarni', 'Amit Vora'],
    strategyType: 'multi-strategy',
    netLongRange: '40-60%',
    marchCrashData: {
      fundReturn: -1.42,
      niftyReturn: -11.30,
      capitalProtected: 87.4,
      alphaVsNifty: 9.88,
      categoryAvg: -2.76,
      vsCategory: 1.34,
      rank: 3,
      totalFunds: 6,
    },
    quizProfile: {
      riskLevel: 'moderate',
      strategyClarity: 'high',
      amcTrust: 'specialist',
      bestFor: ['capital protection', 'global diversification', 'multi-strategy'],
    },
  },

  // 2. Magnum Hybrid Long-Short (SBI)
  {
    id: 'magnum-hybrid-long-short',
    name: 'Magnum Hybrid Long-Short',
    shortName: 'Magnum',
    amc: 'SBI Mutual Fund',
    amcCode: 'SB',
    category: 'Hybrid Long Short',
    categorySlug: 'hybrid-long-short',
    inceptionDate: '2025-10-29',
    inceptionNav: 10.0357,
    currentNav: 10.018,
    ter: 1.20,
    terRegular: 2.05,
    minInvestment: 1000000,
    redemptionFreq: 'Weekly',
    settlement: 'T+3',
    exitLoad: '0.50% if redeemed within 90 days',
    benchmark: 'NIFTY 50 Hybrid Composite Debt 50:50',
    slug: 'magnum-hybrid-long-short',
    seoTitle: 'Magnum SIF by SBI — Hybrid Long Short Fund',
    seoDesc: 'SBI Magnum Hybrid Long-Short SIF. Protected 83.2% of capital when Nifty fell 11.3%.',
    navHistory: [
      { month: 'Oct 2025', nav: 10.0357 },
      { month: 'Nov 2025', nav: 10.08 },
      { month: 'Dec 2025', nav: 10.10 },
      { month: 'Jan 2026', nav: 10.15 },
      { month: 'Feb 2026', nav: 10.21 },
      { month: 'Mar 2026', nav: 10.018 },
      { month: 'Apr 2026', nav: null },
    ],
    monthlyReturns: {
      'Oct 2025': 0.00,
      'Nov 2025': 0.44,
      'Dec 2025': 0.20,
      'Jan 2026': 0.50,
      'Feb 2026': 0.59,
      'Mar 2026': -1.88,
      'Apr 2026': null,
    },
    returns: {
      oneMonth: -1.90,
      threeMonth: -2.38,
      sinceInception: -0.42,
    },
    managers: ['Dinesh Balachandran', 'Mansi Sajeja'],
    strategyType: 'pure-long-short',
    netLongRange: '30-70%',
    marchCrashData: {
      fundReturn: -1.90,
      niftyReturn: -11.30,
      capitalProtected: 83.2,
      alphaVsNifty: 9.40,
      categoryAvg: -2.76,
      vsCategory: 0.86,
      rank: 4,
      totalFunds: 6,
    },
    quizProfile: {
      riskLevel: 'moderate',
      strategyClarity: 'high',
      amcTrust: 'large',
      bestFor: ['capital protection', 'large AMC preference', 'pure long-short'],
    },
  },

  // 3. qSIF Hybrid Long-Short (Quant)
  {
    id: 'qsif-hybrid-long-short',
    name: 'qSIF Hybrid Long-Short',
    shortName: 'qSIF Hybrid',
    amc: 'Quant Mutual Fund',
    amcCode: 'QU',
    category: 'Hybrid Long Short',
    categorySlug: 'hybrid-long-short',
    inceptionDate: '2025-10-20',
    inceptionNav: 10.0189,
    currentNav: 9.9607,
    ter: 1.10,
    terRegular: 1.95,
    minInvestment: 1000000,
    redemptionFreq: 'Weekly',
    settlement: 'T+3',
    exitLoad: '0.50% if redeemed within 90 days',
    benchmark: 'NIFTY 50 Hybrid Composite Debt 50:50',
    slug: 'qsif-hybrid-long-short',
    seoTitle: 'qSIF Hybrid Long-Short by Quant — Analysis',
    seoDesc: 'Quant qSIF Hybrid Long-Short. Alpha Shield 9.2/10 — protected 92.4% of capital in March 2026 crash.',
    navHistory: [
      { month: 'Oct 2025', nav: 10.0189 },
      { month: 'Nov 2025', nav: 10.05 },
      { month: 'Dec 2025', nav: 10.08 },
      { month: 'Jan 2026', nav: 10.10 },
      { month: 'Feb 2026', nav: 10.13 },
      { month: 'Mar 2026', nav: 9.9607 },
      { month: 'Apr 2026', nav: null },
    ],
    monthlyReturns: {
      'Oct 2025': 0.00,
      'Nov 2025': 0.31,
      'Dec 2025': 0.30,
      'Jan 2026': 0.20,
      'Feb 2026': 0.30,
      'Mar 2026': -1.67,
      'Apr 2026': null,
    },
    returns: {
      oneMonth: -0.86,
      threeMonth: -1.70,
      sinceInception: -1.73,
    },
    managers: ['Sanjeev Sharma', 'Ankit Pande'],
    strategyType: 'quantitative',
    netLongRange: '25-75%',
    marchCrashData: {
      fundReturn: -0.86,
      niftyReturn: -11.30,
      capitalProtected: 92.4,
      alphaVsNifty: 10.44,
      categoryAvg: -2.76,
      vsCategory: 1.90,
      rank: 2,
      totalFunds: 6,
    },
    quizProfile: {
      riskLevel: 'moderate',
      strategyClarity: 'medium',
      amcTrust: 'quant',
      bestFor: ['quantitative strategy', 'lowest TER', 'systematic approach'],
    },
  },

  // 4. Titanium Hybrid Long-Short (Tata)
  {
    id: 'titanium-hybrid-long-short',
    name: 'Titanium Hybrid Long-Short',
    shortName: 'Titanium',
    amc: 'Tata Mutual Fund',
    amcCode: 'TA',
    category: 'Hybrid Long Short',
    categorySlug: 'hybrid-long-short',
    inceptionDate: '2025-12-17',
    inceptionNav: 10.0029,
    currentNav: 9.5813,
    ter: 1.15,
    terRegular: 2.00,
    minInvestment: 1000000,
    redemptionFreq: 'Weekly',
    settlement: 'T+3',
    exitLoad: '0.50% if redeemed within 90 days',
    benchmark: 'NIFTY 50 Hybrid Composite Debt 50:50',
    slug: 'titanium-hybrid-long-short',
    seoTitle: 'Titanium SIF by Tata — Hybrid Long Short Fund',
    seoDesc: 'Tata Titanium Hybrid Long-Short SIF. Analysis, NAV and returns on SIFPrime.',
    navHistory: [
      { month: 'Dec 2025', nav: 10.0029 },
      { month: 'Jan 2026', nav: 9.92 },
      { month: 'Feb 2026', nav: 9.85 },
      { month: 'Mar 2026', nav: 9.5813 },
      { month: 'Apr 2026', nav: null },
    ],
    monthlyReturns: {
      'Dec 2025': 0.00,
      'Jan 2026': -0.83,
      'Feb 2026': -0.71,
      'Mar 2026': -2.73,
      'Apr 2026': null,
    },
    returns: {
      oneMonth: -6.16,
      threeMonth: -6.50,
      sinceInception: -5.93,
    },
    managers: ['Rahul Singh', 'Murthy Nagarajan'],
    strategyType: 'pure-long-short',
    netLongRange: '50-80%',
    marchCrashData: {
      fundReturn: -6.16,
      niftyReturn: -11.30,
      capitalProtected: 45.5,
      alphaVsNifty: 5.14,
      categoryAvg: -2.76,
      vsCategory: -3.40,
      rank: 5,
      totalFunds: 6,
    },
    quizProfile: {
      riskLevel: 'aggressive',
      strategyClarity: 'high',
      amcTrust: 'large',
      bestFor: ['large AMC preference', 'higher risk tolerance', 'Tata brand'],
    },
  },

  // 5. Arudha Hybrid Long-Short (Bandhan)
  {
    id: 'arudha-hybrid-long-short',
    name: 'Arudha Hybrid Long-Short',
    shortName: 'Arudha Hybrid',
    amc: 'Bandhan Mutual Fund',
    amcCode: 'BA',
    category: 'Hybrid Long Short',
    categorySlug: 'hybrid-long-short',
    inceptionDate: '2026-02-04',
    inceptionNav: 10.0340,
    currentNav: 10.083,
    ter: 1.25,
    terRegular: 2.10,
    minInvestment: 1000000,
    redemptionFreq: 'Weekly',
    settlement: 'T+3',
    exitLoad: '0.50% if redeemed within 90 days',
    benchmark: 'NIFTY 50 Hybrid Composite Debt 50:50',
    slug: 'arudha-hybrid-long-short',
    seoTitle: 'Arudha SIF by Bandhan — Best Capital Protection',
    seoDesc: 'Bandhan Arudha Hybrid Long-Short SIF returned +0.07% when Nifty fell -11.3%. #1 in capital protection.',
    navHistory: [
      { month: 'Feb 2026', nav: 10.0340 },
      { month: 'Mar 2026', nav: 10.083 },
      { month: 'Apr 2026', nav: null },
    ],
    monthlyReturns: {
      'Feb 2026': 0.00,
      'Mar 2026': 0.49,
      'Apr 2026': null,
    },
    returns: {
      oneMonth: 0.07,
      threeMonth: 0.56,
      sinceInception: 0.56,
    },
    managers: ['Saurabh Bhatia', 'Gautam Kaul'],
    strategyType: 'pure-long-short',
    netLongRange: '20-50%',
    marchCrashData: {
      fundReturn: 0.07,
      niftyReturn: -11.30,
      capitalProtected: 100.6,
      alphaVsNifty: 11.37,
      categoryAvg: -2.76,
      vsCategory: 2.83,
      rank: 1,
      totalFunds: 6,
    },
    quizProfile: {
      riskLevel: 'conservative',
      strategyClarity: 'high',
      amcTrust: 'specialist',
      bestFor: ['maximum capital protection', 'conservative HNI', 'proven hedging'],
    },
  },

  // 6. iSIF Hybrid Long-Short (ICICI Pru)
  {
    id: 'isif-hybrid',
    name: 'iSIF Hybrid Long-Short',
    shortName: 'iSIF Hybrid',
    amc: 'ICICI Prudential',
    amcCode: 'IP',
    category: 'Hybrid Long Short',
    categorySlug: 'hybrid-long-short',
    inceptionDate: '2026-02-05',
    inceptionNav: 10.0179,
    currentNav: 9.4754,
    ter: 1.35,
    terRegular: 2.20,
    minInvestment: 1000000,
    redemptionFreq: 'Daily',
    settlement: 'T+3',
    exitLoad: '0.50% if redeemed within 90 days',
    benchmark: 'NIFTY 50 Hybrid Composite Debt 50:50',
    slug: 'isif/hybrid',
    seoTitle: 'iSIF Hybrid by ICICI Prudential — Analysis',
    seoDesc: 'ICICI Prudential iSIF Hybrid Long-Short. Daily liquidity. Full analysis on SIFPrime.',
    navHistory: [
      { month: 'Feb 2026', nav: 10.0179 },
      { month: 'Mar 2026', nav: 9.4754 },
      { month: 'Apr 2026', nav: null },
    ],
    monthlyReturns: {
      'Feb 2026': 0.00,
      'Mar 2026': -5.41,
      'Apr 2026': null,
    },
    returns: {
      oneMonth: -6.29,
      threeMonth: -7.86,
      sinceInception: -7.86,
    },
    managers: ['Mittul Kalawadia', 'Rohit Lakhotia'],
    strategyType: 'pure-long-short',
    netLongRange: '60-90%',
    marchCrashData: {
      fundReturn: -6.29,
      niftyReturn: -11.30,
      capitalProtected: 44.3,
      alphaVsNifty: 5.01,
      categoryAvg: -2.76,
      vsCategory: -3.53,
      rank: 6,
      totalFunds: 6,
    },
    quizProfile: {
      riskLevel: 'aggressive',
      strategyClarity: 'medium',
      amcTrust: 'large',
      bestFor: ['ICICI brand preference', 'daily liquidity need', 'higher risk tolerance'],
    },
  },

  // 7. Apex Hybrid Long-Short (DSP)
  {
    id: 'apex-hybrid-long-short',
    name: 'Apex Hybrid Long-Short',
    shortName: 'Apex',
    amc: 'DSP Mutual Fund',
    amcCode: 'DS',
    category: 'Hybrid Long Short',
    categorySlug: 'hybrid-long-short',
    inceptionDate: '2026-04-01',
    inceptionNav: 10.00,
    currentNav: 10.03,
    ter: 1.30,
    terRegular: 2.15,
    minInvestment: 1000000,
    redemptionFreq: 'Weekly',
    settlement: 'T+3',
    exitLoad: '0.50% if redeemed within 90 days',
    benchmark: 'NIFTY 50 Hybrid Composite Debt 50:50',
    slug: 'apex-hybrid-long-short',
    seoTitle: 'Apex SIF by DSP — Hybrid Long Short Fund',
    seoDesc: 'DSP Apex Hybrid Long-Short SIF launched April 2026.',
    navHistory: [
      { month: 'Apr 2026', nav: 10.03 },
    ],
    monthlyReturns: {
      'Apr 2026': null,
    },
    returns: {
      oneMonth: null,
      threeMonth: null,
      sinceInception: 0.20,
    },
    managers: ['Atul Bhole', 'Jay Kothari'],
    strategyType: 'multi-strategy',
    netLongRange: '30-60%',
    marchCrashData: {
      fundReturn: null,
      niftyReturn: -11.30,
      capitalProtected: null,
      alphaVsNifty: null,
      categoryAvg: -2.76,
      vsCategory: null,
      rank: null,
      totalFunds: 6,
    },
    quizProfile: {
      riskLevel: 'moderate',
      strategyClarity: 'high',
      amcTrust: 'specialist',
      bestFor: ['new fund opportunity', 'DSP brand', 'multi-strategy'],
    },
  },

  // 8. qSIF Equity Long-Short (Quant)
  {
    id: 'qsif-equity-long-short',
    name: 'qSIF Equity Long-Short',
    shortName: 'qSIF Equity',
    amc: 'Quant Mutual Fund',
    amcCode: 'QU',
    category: 'Equity Long Short',
    categorySlug: 'equity-long-short',
    inceptionDate: '2025-10-08',
    inceptionNav: 10.00,
    currentNav: 9.1473,
    ter: 1.25,
    terRegular: 2.15,
    minInvestment: 1000000,
    redemptionFreq: 'Weekly',
    settlement: 'T+3',
    exitLoad: '0.50% if redeemed within 90 days',
    benchmark: 'Nifty 500',
    slug: 'qsif-equity-long-short',
    seoTitle: 'qSIF Equity Long-Short by Quant — Analysis',
    seoDesc: 'Quant qSIF Equity Long-Short SIF. Full NAV history and returns on SIFPrime.',
    navHistory: [
      { month: 'Oct 2025', nav: 10.00 },
      { month: 'Nov 2025', nav: 9.85 },
      { month: 'Dec 2025', nav: 9.78 },
      { month: 'Jan 2026', nav: 9.72 },
      { month: 'Feb 2026', nav: 9.65 },
      { month: 'Mar 2026', nav: 9.1473 },
      { month: 'Apr 2026', nav: null },
    ],
    monthlyReturns: {
      'Oct 2025': 0.00,
      'Nov 2025': -1.50,
      'Dec 2025': -0.71,
      'Jan 2026': -0.61,
      'Feb 2026': -0.72,
      'Mar 2026': -5.21,
      'Apr 2026': null,
    },
    returns: {
      oneMonth: -8.23,
      threeMonth: -11.68,
      sinceInception: -10.77,
    },
    managers: ['Sanjeev Sharma', 'Vasav Sahgal'],
    strategyType: 'quantitative',
    netLongRange: '50-90%',
    marchCrashData: {
      fundReturn: -8.23,
      niftyReturn: -11.30,
      capitalProtected: 27.2,
      alphaVsNifty: 3.07,
      categoryAvg: -6.31,
      vsCategory: 1.92,
      rank: 2,
      totalFunds: 3,
    },
    quizProfile: {
      riskLevel: 'aggressive',
      strategyClarity: 'medium',
      amcTrust: 'quant',
      bestFor: ['pure equity exposure', 'quantitative approach', 'higher risk/reward'],
    },
  },

  // 9. Diviniti Equity Long-Short (ITI)
  {
    id: 'diviniti-equity-long-short',
    name: 'Diviniti Equity Long-Short',
    shortName: 'Diviniti',
    amc: 'ITI Mutual Fund',
    amcCode: 'IT',
    category: 'Equity Long Short',
    categorySlug: 'equity-long-short',
    inceptionDate: '2025-12-03',
    inceptionNav: 1000.00,
    currentNav: 948.8272,
    ter: 1.40,
    terRegular: 2.30,
    minInvestment: 1000000,
    redemptionFreq: 'Weekly',
    settlement: 'T+3',
    exitLoad: '0.50% if redeemed within 90 days',
    benchmark: 'Nifty 500',
    slug: 'diviniti-equity-long-short',
    seoTitle: 'Diviniti SIF by ITI — Equity Long Short Fund',
    seoDesc: 'ITI Diviniti Equity Long-Short SIF. Best in category in March 2026 crash.',
    navHistory: [
      { month: 'Dec 2025', nav: 1000.00 },
      { month: 'Jan 2026', nav: 988.50 },
      { month: 'Feb 2026', nav: 975.30 },
      { month: 'Mar 2026', nav: 948.8272 },
      { month: 'Apr 2026', nav: null },
    ],
    monthlyReturns: {
      'Dec 2025': 0.00,
      'Jan 2026': -1.15,
      'Feb 2026': -1.33,
      'Mar 2026': -2.72,
      'Apr 2026': null,
    },
    returns: {
      oneMonth: -2.24,
      threeMonth: -5.61,
      sinceInception: -5.24,
    },
    managers: ['George Heber Joseph', 'Pradeep Gokhale'],
    strategyType: 'pure-long-short',
    netLongRange: '50-80%',
    marchCrashData: {
      fundReturn: -2.24,
      niftyReturn: -11.30,
      capitalProtected: 80.2,
      alphaVsNifty: 9.06,
      categoryAvg: -6.31,
      vsCategory: 4.07,
      rank: 1,
      totalFunds: 3,
    },
    quizProfile: {
      riskLevel: 'aggressive',
      strategyClarity: 'high',
      amcTrust: 'boutique',
      bestFor: ['pure equity long-short', 'boutique fund preference', 'experienced managers'],
    },
  },

  // 10. DynaSIF Equity Long-Short (360 ONE)
  {
    id: 'dynasif-equity-long-short',
    name: 'DynaSIF Equity Long-Short',
    shortName: 'DynaSIF Equity',
    amc: '360 ONE Mutual Fund',
    amcCode: '3O',
    category: 'Equity Long Short',
    categorySlug: 'equity-long-short',
    inceptionDate: '2026-02-27',
    inceptionNav: 10.00,
    currentNav: 9.718,
    ter: 1.35,
    terRegular: 2.20,
    minInvestment: 1000000,
    redemptionFreq: 'Weekly',
    settlement: 'T+3',
    exitLoad: '0.50% if redeemed within 90 days',
    benchmark: 'Nifty 500',
    slug: 'dyna-equity-long-short',
    seoTitle: 'DynaSIF Equity Long-Short by 360 ONE',
    seoDesc: '360 ONE DynaSIF Equity Long-Short SIF. NAV and analysis on SIFPrime.',
    navHistory: [
      { month: 'Feb 2026', nav: 10.00 },
      { month: 'Mar 2026', nav: 9.718 },
      { month: 'Apr 2026', nav: null },
    ],
    monthlyReturns: {
      'Feb 2026': 0.00,
      'Mar 2026': -2.82,
      'Apr 2026': null,
    },
    returns: {
      oneMonth: -4.42,
      threeMonth: -4.39,
      sinceInception: -4.39,
    },
    managers: ['Karan Mehta', 'Neeraj Garg'],
    strategyType: 'pure-long-short',
    netLongRange: '40-80%',
    marchCrashData: {
      fundReturn: -4.42,
      niftyReturn: -11.30,
      capitalProtected: 60.9,
      alphaVsNifty: 6.88,
      categoryAvg: -6.31,
      vsCategory: 1.89,
      rank: 2,
      totalFunds: 3,
    },
    quizProfile: {
      riskLevel: 'aggressive',
      strategyClarity: 'high',
      amcTrust: 'boutique',
      bestFor: ['360 ONE brand', 'innovative boutique', 'equity focus'],
    },
  },

  // 11. Arudha Equity Long-Short (Bandhan)
  {
    id: 'arudha-equity-long-short',
    name: 'Arudha Equity Long-Short',
    shortName: 'Arudha Equity',
    amc: 'Bandhan Mutual Fund',
    amcCode: 'BA',
    category: 'Equity Long Short',
    categorySlug: 'equity-long-short',
    inceptionDate: '2026-03-30',
    inceptionNav: 10.00,
    currentNav: 9.959,
    ter: 1.25,
    terRegular: 2.10,
    minInvestment: 1000000,
    redemptionFreq: 'Weekly',
    settlement: 'T+3',
    exitLoad: '0.50% if redeemed within 90 days',
    benchmark: 'Nifty 500',
    slug: 'arudha-equity-long-short',
    seoTitle: 'Arudha Equity SIF by Bandhan — Analysis',
    seoDesc: 'Bandhan Arudha Equity Long-Short SIF. Launched March 2026.',
    navHistory: [
      { month: 'Mar 2026', nav: 10.00 },
      { month: 'Apr 2026', nav: null },
    ],
    monthlyReturns: {
      'Mar 2026': 0.00,
      'Apr 2026': null,
    },
    returns: {
      oneMonth: null,
      threeMonth: null,
      sinceInception: 0.00,
    },
    managers: ['Saurabh Bhatia', 'Gautam Kaul'],
    strategyType: 'pure-long-short',
    netLongRange: '20-60%',
    marchCrashData: {
      fundReturn: null,
      niftyReturn: -11.30,
      capitalProtected: null,
      alphaVsNifty: null,
      categoryAvg: -6.31,
      vsCategory: null,
      rank: null,
      totalFunds: 3,
    },
    quizProfile: {
      riskLevel: 'moderate',
      strategyClarity: 'high',
      amcTrust: 'specialist',
      bestFor: ['new fund entry', 'Bandhan track record', 'equity long-short'],
    },
  },

  // 12. iSIF Ex-Top 100 (ICICI Pru)
  {
    id: 'isif-ex-top-100',
    name: 'iSIF Ex-Top 100',
    shortName: 'iSIF Ex-Top 100',
    amc: 'ICICI Prudential',
    amcCode: 'IP',
    category: 'Equity Ex-Top 100',
    categorySlug: 'ex-top-100',
    inceptionDate: '2026-02-05',
    inceptionNav: 10.00,
    currentNav: 9.28,
    ter: 1.35,
    terRegular: 2.20,
    minInvestment: 1000000,
    redemptionFreq: 'Weekly',
    settlement: 'T+3',
    exitLoad: '0.50% if redeemed within 90 days',
    benchmark: 'Nifty Midcap 150',
    slug: 'sifs/isif/extop100',
    seoTitle: 'iSIF Ex-Top 100 by ICICI Prudential — Analysis',
    seoDesc: 'ICICI Prudential iSIF Ex-Top 100 Long-Short SIF. Mid/small cap focus on SIFPrime.',
    navHistory: [
      { month: 'Feb 2026', nav: 10.00 },
      { month: 'Mar 2026', nav: 9.28 },
      { month: 'Apr 2026', nav: null },
    ],
    monthlyReturns: {
      'Feb 2026': 0.00,
      'Mar 2026': -7.20,
      'Apr 2026': null,
    },
    returns: {
      oneMonth: -7.30,
      threeMonth: -9.71,
      sinceInception: -9.71,
    },
    managers: ['Mittul Kalawadia', 'Sri Sharma'],
    strategyType: 'ex-top-100',
    netLongRange: '60-90%',
    marchCrashData: {
      fundReturn: -7.30,
      niftyReturn: -11.30,
      capitalProtected: 35.4,
      alphaVsNifty: 4.00,
      categoryAvg: -6.79,
      vsCategory: -0.51,
      rank: 2,
      totalFunds: 2,
    },
    quizProfile: {
      riskLevel: 'aggressive',
      strategyClarity: 'high',
      amcTrust: 'large',
      bestFor: ['mid small cap access', 'beyond Nifty 100', 'ICICI brand'],
    },
  },

  // 13. qSIF Ex-Top 100 (Quant)
  {
    id: 'qsif-ex-top-100',
    name: 'qSIF Ex-Top 100',
    shortName: 'qSIF Ex-Top 100',
    amc: 'Quant Mutual Fund',
    amcCode: 'QU',
    category: 'Equity Ex-Top 100',
    categorySlug: 'ex-top-100',
    inceptionDate: '2025-11-13',
    inceptionNav: 10.00,
    currentNav: 8.8418,
    ter: 1.25,
    terRegular: 2.10,
    minInvestment: 1000000,
    redemptionFreq: 'Weekly',
    settlement: 'T+3',
    exitLoad: '0.50% if redeemed within 90 days',
    benchmark: 'Nifty Midcap 150',
    slug: 'qsif-ex-top-100-long-short',
    seoTitle: 'qSIF Ex-Top 100 by Quant — Analysis',
    seoDesc: 'Quant qSIF Ex-Top 100 Long-Short SIF. Mid/small cap beyond Nifty 100 on SIFPrime.',
    navHistory: [
      { month: 'Nov 2025', nav: 10.00 },
      { month: 'Dec 2025', nav: 9.82 },
      { month: 'Jan 2026', nav: 9.65 },
      { month: 'Feb 2026', nav: 9.43 },
      { month: 'Mar 2026', nav: 8.8418 },
      { month: 'Apr 2026', nav: null },
    ],
    monthlyReturns: {
      'Nov 2025': 0.00,
      'Dec 2025': -1.80,
      'Jan 2026': -1.73,
      'Feb 2026': -2.28,
      'Mar 2026': -6.24,
      'Apr 2026': null,
    },
    returns: {
      oneMonth: -6.27,
      threeMonth: -13.03,
      sinceInception: -14.02,
    },
    managers: ['Sanjeev Sharma', 'Vasav Sahgal'],
    strategyType: 'quantitative',
    netLongRange: '50-90%',
    marchCrashData: {
      fundReturn: -6.27,
      niftyReturn: -11.30,
      capitalProtected: 44.5,
      alphaVsNifty: 5.03,
      categoryAvg: -6.79,
      vsCategory: 0.52,
      rank: 1,
      totalFunds: 2,
    },
    quizProfile: {
      riskLevel: 'aggressive',
      strategyClarity: 'medium',
      amcTrust: 'quant',
      bestFor: ['quantitative ex-top-100', 'mid small cap', 'systematic approach'],
    },
  },

  // 14. DynaSIF Active Asset Allocator (360 ONE)
  {
    id: 'dynasif-active-asset-allocator',
    name: 'DynaSIF Active Asset Allocator',
    shortName: 'DynaSIF AAA',
    amc: '360 ONE Mutual Fund',
    amcCode: '3O',
    category: 'Active Asset Allocator',
    categorySlug: 'active-asset-allocator',
    inceptionDate: '2026-03-01',
    inceptionNav: 10.00,
    currentNav: 10.0362,
    ter: 1.30,
    terRegular: 2.15,
    minInvestment: 1000000,
    redemptionFreq: 'Weekly',
    settlement: 'T+3',
    exitLoad: '0.50% if redeemed within 90 days',
    benchmark: 'NIFTY 50 Hybrid Composite Debt 65:35',
    slug: 'dyna-active-asset-allocator',
    seoTitle: 'DynaSIF Active Asset Allocator by 360 ONE',
    seoDesc: '360 ONE DynaSIF Active Asset Allocator SIF. Dynamic equity-debt allocation on SIFPrime.',
    navHistory: [
      { month: 'Mar 2026', nav: 10.00 },
      { month: 'Apr 2026', nav: null },
    ],
    monthlyReturns: {
      'Mar 2026': 0.00,
      'Apr 2026': null,
    },
    returns: {
      oneMonth: null,
      threeMonth: null,
      sinceInception: 0.36,
    },
    managers: ['Karan Mehta', 'Neeraj Garg'],
    strategyType: 'active-asset-allocator',
    netLongRange: 'Dynamic 0-100%',
    marchCrashData: {
      fundReturn: null,
      niftyReturn: -11.30,
      capitalProtected: null,
      alphaVsNifty: null,
      categoryAvg: 0,
      vsCategory: null,
      rank: null,
      totalFunds: 1,
    },
    quizProfile: {
      riskLevel: 'conservative',
      strategyClarity: 'high',
      amcTrust: 'boutique',
      bestFor: ['dynamic allocation', 'conservative HNI', 'flexible mandate'],
    },
  },
];

// Helper functions
export const getSifBySlug = (slug: string) => sifFunds.find(f => f.slug === slug);
export const getSifsByCategory = (cat: string) => sifFunds.filter(f => f.categorySlug === cat);
export const getHybridFunds = () => getSifsByCategory('hybrid-long-short');
export const getEquityFunds = () => getSifsByCategory('equity-long-short');
export const getExTop100Funds = () => getSifsByCategory('ex-top-100');
