export interface SIFund {
  id: string;
  name: string;
  shortName: string;
  amc: string;
  amcCode: string;
  category: string;
  categorySlug: string;
  inceptionDate: string;
  inceptionNav: number;
  currentNav: number;
  ter: number;
  terRegular: number;
  minInvestment: number;
  redemptionFreq: string;
  settlement: string;
  exitLoad: string;
  benchmark: string;
  slug: string;
  seoTitle: string;
  seoDesc: string;
  navHistory: { month: string; nav: number | null }[];
  monthlyReturns: Record<string, number | null>;
  returns: {
    oneMonth: number | null;
    threeMonth: number | null;
    sinceInception: number;
  };
  managers: string[];
  strategyType: string;
  netLongRange: string;
  marchCrashData: {
    fundReturn: number | null;
    benchmarkReturn: number;
    capitalProtected: number | null;
    alphaVsBenchmark: number | null;
    categoryAvg: number;
    vsCategory: number | null;
    rank: number | null;
    totalFunds: number;
  };
  quizProfile: {
    riskLevel: string;
    strategyClarity: string;
    amcTrust: string;
    bestFor: string[];
  };
}

export const sifFunds: SIFund[] = [
  // 1. Altiva Hybrid Long-Short (Edelweiss)
  {
    id: 'altiva-hybrid-long-short',
    name: 'Altiva Hybrid Long-Short',
    shortName: 'Altiva',
    amc: 'Edelweiss',
    amcCode: 'ED',
    category: 'Hybrid Long Short',
    categorySlug: 'hybrid-long-short',
    inceptionDate: '2025-10-24',
    inceptionNav: 10.0102,
    currentNav: 10.5455,
    ter: 1.35,
    terRegular: 2.25,
    minInvestment: 1000000,
    redemptionFreq: '2x per week (Mon & Wed)',
    settlement: 'T+3',
    exitLoad: '0.50% if redeemed within 90 days',
    benchmark: 'NIFTY 50 Hybrid Composite Debt 50:50',
    slug: 'altiva-hybrid-long-short',
    seoTitle: 'Altiva SIF by Edelweiss — Returns, NAV & Analysis',
    seoDesc: 'Altiva Hybrid Long-Short SIF returned +2.10% since inception while its benchmark fell 6.35% in March 2026.',
    navHistory: [
      { month: 'Oct 2025', nav: 10.0188 },
      { month: 'Nov 2025', nav: 10.1204 },
      { month: 'Dec 2025', nav: 10.2931 },
      { month: 'Jan 2026', nav: 10.3066 },
      { month: 'Feb 2026', nav: 10.3801 },
      { month: 'Mar 2026', nav: 10.2214 },
      { month: 'Apr 2026', nav: 10.5455 },
    ],
    monthlyReturns: {
      'Oct 2025': 0.09,
      'Nov 2025': 1.01,
      'Dec 2025': 1.71,
      'Jan 2026': 0.13,
      'Feb 2026': 0.71,
      'Mar 2026': -1.53,
      'Apr 2026': 3.17,
    },
    returns: {
      oneMonth: 3.17,
      threeMonth: 2.32,
      sinceInception: 5.35,
    },
    managers: ['Bhavesh Jain', 'Bharat Lahoti', 'Dhawal Dalal', 'Pranavi Kulkarni', 'Amit Vora'],
    strategyType: 'multi-strategy',
    netLongRange: '40-60%',
    marchCrashData: {
      fundReturn: -1.42,
      benchmarkReturn: -6.35,
      capitalProtected: 77.6,
      alphaVsBenchmark: 4.93,
      categoryAvg: -2.76,
      vsCategory: 1.34,
      rank: 3,
      totalFunds: 6,
    },
    quizProfile: {
      riskLevel: 'moderate',
      strategyClarity: 'high',
      amcTrust: 'specialist',
      bestFor: ['capital protection', 'global diversification', 'multi-strategy'],
    },
  },

  // 2. Magnum Hybrid Long-Short (SBI)
  {
    id: 'magnum-hybrid-long-short',
    name: 'Magnum Hybrid Long-Short',
    shortName: 'Magnum',
    amc: 'SBI Mutual Fund',
    amcCode: 'SB',
    category: 'Hybrid Long Short',
    categorySlug: 'hybrid-long-short',
    inceptionDate: '2025-10-29',
    inceptionNav: 10.0357,
    currentNav: 10.2218,
    ter: 1.20,
    terRegular: 2.05,
    minInvestment: 1000000,
    redemptionFreq: 'Weekly',
    settlement: 'T+3',
    exitLoad: '0.50% if redeemed within 90 days',
    benchmark: 'NIFTY 50 Hybrid Composite Debt 50:50',
    slug: 'magnum-hybrid-long-short',
    seoTitle: 'Magnum SIF by SBI — Hybrid Long Short Fund',
    seoDesc: 'SBI Magnum Hybrid Long-Short SIF. Protected 70.1% of capital vs benchmark in March 2026 crash.',
    navHistory: [
      { month: 'Oct 2025', nav: 10.0017 },
      { month: 'Nov 2025', nav: 10.1262 },
      { month: 'Dec 2025', nav: 10.2223 },
      { month: 'Jan 2026', nav: 10.1372 },
      { month: 'Feb 2026', nav: 10.2152 },
      { month: 'Mar 2026', nav: 9.9944 },
      { month: 'Apr 2026', nav: 10.2218 },
    ],
    monthlyReturns: {
      'Oct 2025': -0.34,
      'Nov 2025': 1.24,
      'Dec 2025': 0.95,
      'Jan 2026': -0.83,
      'Feb 2026': 0.77,
      'Mar 2026': -2.16,
      'Apr 2026': 2.28,
    },
    returns: {
      oneMonth: 2.28,
      threeMonth: 0.84,
      sinceInception: 1.85,
    },
    managers: ['Dinesh Balachandran', 'Mansi Sajeja'],
    strategyType: 'pure-long-short',
    netLongRange: '30-70%',
    marchCrashData: {
      fundReturn: -1.90,
      benchmarkReturn: -6.35,
      capitalProtected: 70.1,
      alphaVsBenchmark: 4.45,
      categoryAvg: -2.76,
      vsCategory: 0.86,
      rank: 4,
      totalFunds: 6,
    },
    quizProfile: {
      riskLevel: 'moderate',
      strategyClarity: 'high',
      amcTrust: 'large',
      bestFor: ['capital protection', 'large AMC preference', 'pure long-short'],
    },
  },

  // 3. qSIF Hybrid Long-Short (Quant)
  {
    id: 'qsif-hybrid-long-short',
    name: 'qSIF Hybrid Long-Short',
    shortName: 'qSIF Hybrid',
    amc: 'Quant Mutual Fund',
    amcCode: 'QU',
    category: 'Hybrid Long Short',
    categorySlug: 'hybrid-long-short',
    inceptionDate: '2025-10-20',
    inceptionNav: 10.0189,
    currentNav: 10.5297,
    ter: 1.10,
    terRegular: 1.95,
    minInvestment: 1000000,
    redemptionFreq: 'Tuesday & Wednesday',
    settlement: 'T+3',
    exitLoad: '1% if redeemed within 15 days; Nil after',
    benchmark: 'NIFTY 50 Hybrid Composite Debt 50:50',
    slug: 'qsif-hybrid-long-short',
    seoTitle: 'qSIF Hybrid Long-Short by Quant — Analysis',
    seoDesc: 'Quant qSIF Hybrid Long-Short. Alpha Shield 9.2/10 — protected 92.4% of capital in March 2026 crash.',
    navHistory: [
      { month: 'Oct 2025', nav: 10.0652 },
      { month: 'Nov 2025', nav: 10.0266 },
      { month: 'Dec 2025', nav: 10.0186 },
      { month: 'Jan 2026', nav: 9.8890 },
      { month: 'Feb 2026', nav: 9.9368 },
      { month: 'Mar 2026', nav: 9.8465 },
      { month: 'Apr 2026', nav: 10.5297 },
    ],
    monthlyReturns: {
      'Oct 2025': 0.46,
      'Nov 2025': -0.38,
      'Dec 2025': -0.08,
      'Jan 2026': -1.29,
      'Feb 2026': 0.48,
      'Mar 2026': -0.91,
      'Apr 2026': 6.94,
    },
    returns: {
      oneMonth: 6.94,
      threeMonth: 6.48,
      sinceInception: 5.10,
    },
    managers: ['Sandeep Tandon', 'Lokesh Garg', 'Ankit Pande', 'Sameer Kate', 'Sanjeev Sharma'],
    strategyType: 'quantitative',
    netLongRange: '25-75%',
    marchCrashData: {
      fundReturn: -0.86,
      benchmarkReturn: -6.35,
      capitalProtected: 86.5,
      alphaVsBenchmark: 5.49,
      categoryAvg: -2.76,
      vsCategory: 1.90,
      rank: 2,
      totalFunds: 6,
    },
    quizProfile: {
      riskLevel: 'moderate',
      strategyClarity: 'medium',
      amcTrust: 'quant',
      bestFor: ['quantitative strategy', 'lowest TER', 'systematic approach'],
    },
  },

  // 4. Titanium Hybrid Long-Short (Tata)
  {
    id: 'titanium-hybrid-long-short',
    name: 'Titanium Hybrid Long-Short',
    shortName: 'Titanium',
    amc: 'Tata Mutual Fund',
    amcCode: 'TA',
    category: 'Hybrid Long Short',
    categorySlug: 'hybrid-long-short',
    inceptionDate: '2025-12-17',
    inceptionNav: 10.0029,
    currentNav: 9.9291,
    ter: 1.15,
    terRegular: 2.00,
    minInvestment: 1000000,
    redemptionFreq: 'Weekly',
    settlement: 'T+3',
    exitLoad: '0.50% if redeemed within 90 days',
    benchmark: 'NIFTY 50 Hybrid Composite Debt 50:50',
    slug: 'titanium-hybrid-long-short',
    seoTitle: 'Titanium SIF by Tata — Hybrid Long Short Fund',
    seoDesc: 'Tata Titanium Hybrid Long-Short SIF. Analysis, NAV and returns on SIFPrime.',
    navHistory: [
      { month: 'Dec 2025', nav: 10.0668 },
      { month: 'Jan 2026', nav: 9.9637 },
      { month: 'Feb 2026', nav: 10.1052 },
      { month: 'Mar 2026', nav: 9.4106 },
      { month: 'Apr 2026', nav: 9.9291 },
    ],
    monthlyReturns: {
      'Dec 2025': 0.64,
      'Jan 2026': -1.02,
      'Feb 2026': 1.42,
      'Mar 2026': -6.87,
      'Apr 2026': 5.51,
    },
    returns: {
      oneMonth: 5.51,
      threeMonth: -0.35,
      sinceInception: -0.74,
    },
    managers: ['Rahul Singh', 'Murthy Nagarajan'],
    strategyType: 'pure-long-short',
    netLongRange: '50-80%',
    marchCrashData: {
      fundReturn: -6.16,
      benchmarkReturn: -6.35,
      capitalProtected: 3.0,
      alphaVsBenchmark: 0.19,
      categoryAvg: -2.76,
      vsCategory: -3.40,
      rank: 5,
      totalFunds: 6,
    },
    quizProfile: {
      riskLevel: 'aggressive',
      strategyClarity: 'high',
      amcTrust: 'large',
      bestFor: ['large AMC preference', 'higher risk tolerance', 'Tata brand'],
    },
  },

  // 5. Arudha Hybrid Long-Short (Bandhan)
  {
    id: 'arudha-hybrid-long-short',
    name: 'Arudha Hybrid Long-Short',
    shortName: 'Arudha Hybrid',
    amc: 'Bandhan Mutual Fund',
    amcCode: 'BA',
    category: 'Hybrid Long Short',
    categorySlug: 'hybrid-long-short',
    inceptionDate: '2026-02-04',
    inceptionNav: 10.0340,
    currentNav: 10.1290,
    ter: 1.25,
    terRegular: 2.10,
    minInvestment: 1000000,
    redemptionFreq: 'Weekly',
    settlement: 'T+3',
    exitLoad: '0.50% if redeemed within 90 days',
    benchmark: 'NIFTY 50 Hybrid Composite Debt 50:50',
    slug: 'arudha-hybrid-long-short',
    seoTitle: 'Arudha SIF by Bandhan — Best Capital Protection',
    seoDesc: 'Bandhan Arudha Hybrid Long-Short SIF returned +0.07% when benchmark fell -6.35%. #1 in capital protection.',
    navHistory: [
      { month: 'Feb 2026', nav: 10.0790 },
      { month: 'Mar 2026', nav: 10.0910 },
      { month: 'Apr 2026', nav: 10.1290 },
    ],
    monthlyReturns: {
      'Feb 2026': 0.45,
      'Mar 2026': 0.12,
      'Apr 2026': 0.38,
    },
    returns: {
      oneMonth: 0.38,
      threeMonth: null,
      sinceInception: 0.95,
    },
    managers: ['Saurabh Bhatia', 'Gautam Kaul'],
    strategyType: 'pure-long-short',
    netLongRange: '20-50%',
    marchCrashData: {
      fundReturn: 0.07,
      benchmarkReturn: -6.35,
      capitalProtected: 100.0,
      alphaVsBenchmark: 6.42,
      categoryAvg: -2.76,
      vsCategory: 2.83,
      rank: 1,
      totalFunds: 6,
    },
    quizProfile: {
      riskLevel: 'conservative',
      strategyClarity: 'high',
      amcTrust: 'specialist',
      bestFor: ['maximum capital protection', 'conservative HNI', 'proven hedging'],
    },
  },

  // 6. iSIF Hybrid Long-Short (ICICI Pru)
  {
    id: 'isif-hybrid',
    name: 'iSIF Hybrid Long-Short',
    shortName: 'iSIF Hybrid',
    amc: 'ICICI Prudential',
    amcCode: 'IP',
    category: 'Hybrid Long Short',
    categorySlug: 'hybrid-long-short',
    inceptionDate: '2026-02-05',
    inceptionNav: 10.0179,
    currentNav: 9.9185,
    ter: 1.35,
    terRegular: 2.20,
    minInvestment: 1000000,
    redemptionFreq: 'Daily',
    settlement: 'T+3',
    exitLoad: '0.50% if redeemed within 90 days',
    benchmark: 'NIFTY 50 Hybrid Composite Debt 50:50',
    slug: 'isif/hybrid',
    seoTitle: 'iSIF Hybrid by ICICI Prudential — Analysis',
    seoDesc: 'ICICI Prudential iSIF Hybrid Long-Short. Daily liquidity. Full analysis on SIFPrime.',
    navHistory: [
      { month: 'Feb 2026', nav: 9.9585 },
      { month: 'Mar 2026', nav: 9.2304 },
      { month: 'Apr 2026', nav: 9.9185 },
    ],
    monthlyReturns: {
      'Feb 2026': -0.59,
      'Mar 2026': -7.31,
      'Apr 2026': 7.45,
    },
    returns: {
      oneMonth: 7.45,
      threeMonth: null,
      sinceInception: -0.99,
    },
    managers: ['Mittul Kalawadia', 'Rohit Lakhotia'],
    strategyType: 'pure-long-short',
    netLongRange: '60-90%',
    marchCrashData: {
      fundReturn: -6.29,
      benchmarkReturn: -6.35,
      capitalProtected: 0.9,
      alphaVsBenchmark: 0.06,
      categoryAvg: -2.76,
      vsCategory: -3.53,
      rank: 6,
      totalFunds: 6,
    },
    quizProfile: {
      riskLevel: 'aggressive',
      strategyClarity: 'medium',
      amcTrust: 'large',
      bestFor: ['ICICI brand preference', 'daily liquidity need', 'higher risk tolerance'],
    },
  },

  // 7. Apex Hybrid Long-Short (Aditya Birla Sun Life)
  {
    id: 'apex-hybrid-long-short',
    name: 'Apex Hybrid Long-Short',
    shortName: 'Apex',
    amc: 'Aditya Birla Sun Life Mutual Fund',
    amcCode: 'AB',
    category: 'Hybrid Long Short',
    categorySlug: 'hybrid-long-short',
    inceptionDate: '2026-03-30',
    inceptionNav: 10.0200,
    currentNav: 10.0600,
    ter: 1.30,
    terRegular: 2.15,
    minInvestment: 1000000,
    redemptionFreq: 'Weekly',
    settlement: 'T+3',
    exitLoad: '0.50% if redeemed within 90 days',
    benchmark: 'NIFTY 50 Hybrid Composite Debt 50:50',
    slug: 'apex-hybrid-long-short',
    seoTitle: 'Apex SIF by Aditya Birla Sun Life — Hybrid Long Short Fund',
    seoDesc: 'Aditya Birla Sun Life Apex Hybrid Long-Short SIF launched April 2026.',
    navHistory: [
      { month: 'Mar 2026', nav: 10.0200 },
      { month: 'Apr 2026', nav: 10.0600 },
    ],
    monthlyReturns: {
      'Mar 2026': 0.00,
      'Apr 2026': 0.40,
    },
    returns: {
      oneMonth: 0.40,
      threeMonth: null,
      sinceInception: 0.40,
    },
    managers: ['Lovelish Solanki', 'Mohit Sharma'],
    strategyType: 'multi-strategy',
    netLongRange: '30-60%',
    marchCrashData: {
      fundReturn: null,
      benchmarkReturn: -6.35,
      capitalProtected: null,
      alphaVsBenchmark: null,
      categoryAvg: -2.76,
      vsCategory: null,
      rank: null,
      totalFunds: 6,
    },
    quizProfile: {
      riskLevel: 'moderate',
      strategyClarity: 'high',
      amcTrust: 'specialist',
      bestFor: ['new fund opportunity', 'Aditya Birla brand', 'multi-strategy'],
    },
  },

  // 8. qSIF Equity Long-Short (Quant)
  {
    id: 'qsif-equity-long-short',
    name: 'qSIF Equity Long-Short',
    shortName: 'qSIF Equity',
    amc: 'Quant Mutual Fund',
    amcCode: 'QU',
    category: 'Equity Long Short',
    categorySlug: 'equity-long-short',
    inceptionDate: '2025-10-08',
    inceptionNav: 10.0054,
    currentNav: 10.1492,
    ter: 1.25,
    terRegular: 2.15,
    minInvestment: 1000000,
    redemptionFreq: 'Weekly',
    settlement: 'T+3',
    exitLoad: '0.50% if redeemed within 90 days',
    benchmark: 'Nifty 500',
    slug: 'qsif-equity-long-short',
    seoTitle: 'qSIF Equity Long-Short by Quant — Analysis',
    seoDesc: 'Quant qSIF Equity Long-Short SIF. Full NAV history and returns on SIFPrime.',
    navHistory: [
      { month: 'Oct 2025', nav: 10.1415 },
      { month: 'Nov 2025', nav: 10.1182 },
      { month: 'Dec 2025', nav: 10.0599 },
      { month: 'Jan 2026', nav: 9.7259 },
      { month: 'Feb 2026', nav: 9.8056 },
      { month: 'Mar 2026', nav: 8.9277 },
      { month: 'Apr 2026', nav: 10.1492 },
    ],
    monthlyReturns: {
      'Oct 2025': 1.36,
      'Nov 2025': -0.23,
      'Dec 2025': -0.58,
      'Jan 2026': -3.32,
      'Feb 2026': 0.82,
      'Mar 2026': -8.95,
      'Apr 2026': 13.68,
    },
    returns: {
      oneMonth: 13.68,
      threeMonth: 4.35,
      sinceInception: 1.44,
    },
    managers: ['Sanjeev Sharma', 'Vasav Sahgal'],
    strategyType: 'quantitative',
    netLongRange: '50-90%',
    marchCrashData: {
      fundReturn: -8.23,
      benchmarkReturn: -11.36,
      capitalProtected: 27.6,
      alphaVsBenchmark: 3.13,
      categoryAvg: -6.31,
      vsCategory: 1.92,
      rank: 2,
      totalFunds: 3,
    },
    quizProfile: {
      riskLevel: 'aggressive',
      strategyClarity: 'medium',
      amcTrust: 'quant',
      bestFor: ['pure equity exposure', 'quantitative approach', 'higher risk/reward'],
    },
  },

  // 9. Diviniti Equity Long-Short (ITI)
  {
    id: 'diviniti-equity-long-short',
    name: 'Diviniti Equity Long-Short',
    shortName: 'Diviniti',
    amc: 'ITI Mutual Fund',
    amcCode: 'IT',
    category: 'Equity Long Short',
    categorySlug: 'equity-long-short',
    inceptionDate: '2025-12-03',
    inceptionNav: 1000.953,
    currentNav: 955.1524,
    ter: 1.40,
    terRegular: 2.30,
    minInvestment: 1000000,
    redemptionFreq: 'Weekly',
    settlement: 'T+3',
    exitLoad: '0.50% if redeemed within 90 days',
    benchmark: 'Nifty 500',
    slug: 'diviniti-equity-long-short',
    seoTitle: 'Diviniti SIF by ITI — Equity Long Short Fund',
    seoDesc: 'ITI Diviniti Equity Long-Short SIF. Best in category in March 2026 crash.',
    navHistory: [
      { month: 'Dec 2025', nav: 1003.5044 },
      { month: 'Jan 2026', nav: 991.1992 },
      { month: 'Feb 2026', nav: 977.6434 },
      { month: 'Mar 2026', nav: 948.4515 },
      { month: 'Apr 2026', nav: 955.1524 },
    ],
    monthlyReturns: {
      'Dec 2025': 0.25,
      'Jan 2026': -1.23,
      'Feb 2026': -1.37,
      'Mar 2026': -2.99,
      'Apr 2026': 0.71,
    },
    returns: {
      oneMonth: 0.71,
      threeMonth: -3.64,
      sinceInception: -4.58,
    },
    managers: ['George Heber Joseph', 'Pradeep Gokhale'],
    strategyType: 'pure-long-short',
    netLongRange: '50-80%',
    marchCrashData: {
      fundReturn: -2.24,
      benchmarkReturn: -11.36,
      capitalProtected: 80.3,
      alphaVsBenchmark: 9.12,
      categoryAvg: -6.31,
      vsCategory: 4.07,
      rank: 1,
      totalFunds: 3,
    },
    quizProfile: {
      riskLevel: 'aggressive',
      strategyClarity: 'high',
      amcTrust: 'boutique',
      bestFor: ['pure equity long-short', 'boutique fund preference', 'experienced managers'],
    },
  },

  // 10. DynaSIF Equity Long-Short (360 ONE)
  {
    id: 'dynasif-equity-long-short',
    name: 'DynaSIF Equity Long-Short',
    shortName: 'DynaSIF Equity',
    amc: '360 ONE Mutual Fund',
    amcCode: '3O',
    category: 'Equity Long Short',
    categorySlug: 'equity-long-short',
    inceptionDate: '2026-02-27',
    inceptionNav: 10.0072,
    currentNav: 10.1990,
    ter: 1.35,
    terRegular: 2.20,
    minInvestment: 1000000,
    redemptionFreq: 'Weekly',
    settlement: 'T+3',
    exitLoad: '0.50% if redeemed within 90 days',
    benchmark: 'Nifty 500',
    slug: 'dyna-equity-long-short',
    seoTitle: 'DynaSIF Equity Long-Short by 360 ONE',
    seoDesc: '360 ONE DynaSIF Equity Long-Short SIF. NAV and analysis on SIFPrime.',
    navHistory: [
      { month: 'Feb 2026', nav: 10.0072 },
      { month: 'Mar 2026', nav: 9.5681 },
      { month: 'Apr 2026', nav: 10.1990 },
    ],
    monthlyReturns: {
      'Feb 2026': 0.00,
      'Mar 2026': -4.39,
      'Apr 2026': 6.59,
    },
    returns: {
      oneMonth: 6.59,
      threeMonth: null,
      sinceInception: 1.92,
    },
    managers: ['Karan Mehta', 'Neeraj Garg'],
    strategyType: 'pure-long-short',
    netLongRange: '40-80%',
    marchCrashData: {
      fundReturn: -4.42,
      benchmarkReturn: -11.36,
      capitalProtected: 61.1,
      alphaVsBenchmark: 6.94,
      categoryAvg: -6.31,
      vsCategory: 1.89,
      rank: 2,
      totalFunds: 3,
    },
    quizProfile: {
      riskLevel: 'aggressive',
      strategyClarity: 'high',
      amcTrust: 'boutique',
      bestFor: ['360 ONE brand', 'innovative boutique', 'equity focus'],
    },
  },

  // 11. Arudha Equity Long-Short (Bandhan)
  {
    id: 'arudha-equity-long-short',
    name: 'Arudha Equity Long-Short',
    shortName: 'Arudha Equity',
    amc: 'Bandhan Mutual Fund',
    amcCode: 'BA',
    category: 'Equity Long Short',
    categorySlug: 'equity-long-short',
    inceptionDate: '2026-03-30',
    inceptionNav: 9.8260,
    currentNav: 10.1630,
    ter: 1.25,
    terRegular: 2.10,
    minInvestment: 1000000,
    redemptionFreq: 'Daily',
    settlement: 'T+3',
    exitLoad: '0.50% if redeemed within 30 days; Nil after',
    benchmark: 'Nifty 500 TRI',
    slug: 'arudha-equity-long-short',
    seoTitle: 'Arudha Equity SIF by Bandhan — Analysis',
    seoDesc: 'Bandhan Arudha Equity Long-Short SIF. Launched March 2026.',
    navHistory: [
      { month: 'Mar 2026', nav: 9.8270 },
      { month: 'Apr 2026', nav: 10.1630 },
    ],
    monthlyReturns: {
      'Mar 2026': 0.01,
      'Apr 2026': 3.42,
    },
    returns: {
      oneMonth: 3.42,
      threeMonth: null,
      sinceInception: 3.43,
    },
    managers: ['Nilesh Saha', 'Brijesh Shah'],
    strategyType: 'long-biased',
    netLongRange: '55-100%',
    marchCrashData: {
      fundReturn: null,
      benchmarkReturn: -11.36,
      capitalProtected: null,
      alphaVsBenchmark: null,
      categoryAvg: -6.31,
      vsCategory: null,
      rank: null,
      totalFunds: 3,
    },
    quizProfile: {
      riskLevel: 'moderate',
      strategyClarity: 'high',
      amcTrust: 'specialist',
      bestFor: ['new fund entry', 'Bandhan track record', 'equity long-short'],
    },
  },

  // 12. iSIF Ex-Top 100 (ICICI Pru)
  {
    id: 'isif-ex-top-100',
    name: 'iSIF Ex-Top 100',
    shortName: 'iSIF Ex-Top 100',
    amc: 'ICICI Prudential',
    amcCode: 'IP',
    category: 'Equity Ex-Top 100',
    categorySlug: 'ex-top-100',
    inceptionDate: '2026-02-05',
    inceptionNav: 10.00,
    currentNav: 9.28,
    ter: 1.35,
    terRegular: 2.20,
    minInvestment: 1000000,
    redemptionFreq: 'Weekly',
    settlement: 'T+3',
    exitLoad: '0.50% if redeemed within 90 days',
    benchmark: 'Nifty Midcap 150',
    slug: 'sifs/isif/extop100',
    seoTitle: 'iSIF Ex-Top 100 by ICICI Prudential — Analysis',
    seoDesc: 'ICICI Prudential iSIF Ex-Top 100 Long-Short SIF. Mid/small cap focus on SIFPrime.',
    navHistory: [
      { month: 'Feb 2026', nav: 10.00 },
      { month: 'Mar 2026', nav: 9.28 },
      { month: 'Apr 2026', nav: null },
    ],
    monthlyReturns: {
      'Feb 2026': 0.00,
      'Mar 2026': -7.20,
      'Apr 2026': null,
    },
    returns: {
      oneMonth: -7.30,
      threeMonth: -9.71,
      sinceInception: -7.20,
    },
    managers: ['Mittul Kalawadia', 'Sri Sharma'],
    strategyType: 'ex-top-100',
    netLongRange: '60-90%',
    marchCrashData: {
      fundReturn: -7.30,
      benchmarkReturn: -11.06,
      capitalProtected: 34.0,
      alphaVsBenchmark: 3.76,
      categoryAvg: -6.79,
      vsCategory: -0.51,
      rank: 2,
      totalFunds: 2,
    },
    quizProfile: {
      riskLevel: 'aggressive',
      strategyClarity: 'high',
      amcTrust: 'large',
      bestFor: ['mid small cap access', 'beyond Nifty 100', 'ICICI brand'],
    },
  },

  // 13. qSIF Ex-Top 100 (Quant)
  {
    id: 'qsif-ex-top-100',
    name: 'qSIF Ex-Top 100',
    shortName: 'qSIF Ex-Top 100',
    amc: 'Quant Mutual Fund',
    amcCode: 'QU',
    category: 'Equity Ex-Top 100',
    categorySlug: 'ex-top-100',
    inceptionDate: '2025-11-13',
    inceptionNav: 10.00,
    currentNav: 8.8418,
    ter: 1.25,
    terRegular: 2.10,
    minInvestment: 1000000,
    redemptionFreq: 'Weekly',
    settlement: 'T+3',
    exitLoad: '0.50% if redeemed within 90 days',
    benchmark: 'Nifty Midcap 150',
    slug: 'qsif-ex-top-100-long-short',
    seoTitle: 'qSIF Ex-Top 100 by Quant — Analysis',
    seoDesc: 'Quant qSIF Ex-Top 100 Long-Short SIF. Mid/small cap beyond Nifty 100 on SIFPrime.',
    navHistory: [
      { month: 'Nov 2025', nav: 10.00 },
      { month: 'Dec 2025', nav: 9.82 },
      { month: 'Jan 2026', nav: 9.65 },
      { month: 'Feb 2026', nav: 9.43 },
      { month: 'Mar 2026', nav: 8.8418 },
      { month: 'Apr 2026', nav: null },
    ],
    monthlyReturns: {
      'Nov 2025': 0.00,
      'Dec 2025': -1.80,
      'Jan 2026': -1.73,
      'Feb 2026': -2.28,
      'Mar 2026': -6.24,
      'Apr 2026': null,
    },
    returns: {
      oneMonth: -6.27,
      threeMonth: -13.03,
      sinceInception: -11.58,
    },
    managers: ['Sanjeev Sharma', 'Vasav Sahgal'],
    strategyType: 'quantitative',
    netLongRange: '50-90%',
    marchCrashData: {
      fundReturn: -6.27,
      benchmarkReturn: -11.06,
      capitalProtected: 43.3,
      alphaVsBenchmark: 4.79,
      categoryAvg: -6.79,
      vsCategory: 0.52,
      rank: 1,
      totalFunds: 2,
    },
    quizProfile: {
      riskLevel: 'aggressive',
      strategyClarity: 'medium',
      amcTrust: 'quant',
      bestFor: ['quantitative ex-top-100', 'mid small cap', 'systematic approach'],
    },
  },

  // 14. DynaSIF Active Asset Allocator (360 ONE)
  {
    id: 'dynasif-active-asset-allocator',
    name: 'DynaSIF Active Asset Allocator',
    shortName: 'DynaSIF AAA',
    amc: '360 ONE Mutual Fund',
    amcCode: '3O',
    category: 'Active Asset Allocator',
    categorySlug: 'active-asset-allocator',
    inceptionDate: '2026-03-01',
    inceptionNav: 10.00,
    currentNav: 10.0362,
    ter: 1.30,
    terRegular: 2.15,
    minInvestment: 1000000,
    redemptionFreq: 'Weekly',
    settlement: 'T+3',
    exitLoad: '0.50% if redeemed within 90 days',
    benchmark: 'NIFTY 50 Hybrid Composite Debt 65:35',
    slug: 'dyna-active-asset-allocator',
    seoTitle: 'DynaSIF Active Asset Allocator by 360 ONE',
    seoDesc: '360 ONE DynaSIF Active Asset Allocator SIF. Dynamic equity-debt allocation on SIFPrime.',
    navHistory: [
      { month: 'Mar 2026', nav: 10.00 },
      { month: 'Apr 2026', nav: null },
    ],
    monthlyReturns: {
      'Mar 2026': 0.00,
      'Apr 2026': null,
    },
    returns: {
      oneMonth: null,
      threeMonth: null,
      sinceInception: 0.36,
    },
    managers: ['Karan Mehta', 'Neeraj Garg'],
    strategyType: 'active-asset-allocator',
    netLongRange: 'Dynamic 0-100%',
    marchCrashData: {
      fundReturn: null,
      benchmarkReturn: -7.84,
      capitalProtected: null,
      alphaVsBenchmark: null,
      categoryAvg: 0,
      vsCategory: null,
      rank: null,
      totalFunds: 1,
    },
    quizProfile: {
      riskLevel: 'conservative',
      strategyClarity: 'high',
      amcTrust: 'boutique',
      bestFor: ['dynamic allocation', 'conservative HNI', 'flexible mandate'],
    },
  },
];

// Helper functions
export const getSifBySlug = (slug: string) => sifFunds.find(f => f.slug === slug);
export const getSifsByCategory = (cat: string) => sifFunds.filter(f => f.categorySlug === cat);
export const getHybridFunds = () => getSifsByCategory('hybrid-long-short');
export const getEquityFunds = () => getSifsByCategory('equity-long-short');
export const getExTop100Funds = () => getSifsByCategory('ex-top-100');

// Peers = funds in same category, excluding self
export const getPeers = (slug: string) => {
  const self = getSifBySlug(slug);
  if (!self) return [];
  return sifFunds.filter(f => f.categorySlug === self.categorySlug && f.slug !== slug);
};

// Format a return number as "+X.XX%" / "-X.XX%"
export const fmtPct = (n: number | null | undefined, digits = 2) => {
  if (n === null || n === undefined) return "—";
  const sign = n > 0 ? "+" : "";
  return `${sign}${n.toFixed(digits)}%`;
};
